#!/bin/sh

set -e

tmp=$(mktemp)
trap "rm $tmp" EXIT INT

texindy --out-file $tmp --stdin <<__EOF__
\indexentry{test}{1}
__EOF__

diff -u $tmp - <<__EOF__
\begin{theindex}

  \textbf{T}
  \item test, 1

\end{theindex}
__EOF__
