#! /bin/sh /usr/share/dpatch/dpatch-run
## fix-FHS.dpatch by Jörg Sommer <joerg@alea.gnuu.de>
##
## DP: All files below /usr/lib/xindy/modules/ are architecture independent
## DP: and therefor need to be below /usr/share/ as forced by the FHS.

@DPATCH@
---
 make-rules/alphabets/Makefile.in |    2 +-
 make-rules/inputenc/Makefile.in  |    2 +-
 make-rules/styles/Makefile.in    |    2 +-
 modules/base/Makefile.in         |    2 +-
 modules/class/Makefile.in        |    2 +-
 modules/lang/german/Makefile.in  |    2 +-
 modules/lang/latin/Makefile.in   |    2 +-
 modules/ord/Makefile.in          |    2 +-
 modules/rules/Makefile.in        |    2 +-
 modules/styles/Makefile.in       |    2 +-
 user-commands/xindy.in           |   12 +++++++-----
 11 files changed, 17 insertions(+), 15 deletions(-)

--- xindy.git.orig/make-rules/alphabets/Makefile.in
+++ xindy.git/make-rules/alphabets/Makefile.in
@@ -253,7 +253,7 @@
 top_build_prefix = @top_build_prefix@
 top_builddir = @top_builddir@
 top_srcdir = @top_srcdir@
-langdir = $(pkglibdir)/modules/lang
+langdir = $(pkgdatadir)/lang
 DISTCLEANFILES = albanian/utf8.pl belarusian/utf8.pl bulgarian/utf8.pl \
 	croatian/utf8.pl czech/utf8.pl danish/utf8.pl \
 	dutch/ij-as-ij-utf8.pl dutch/ij-as-y-utf8.pl english/utf8.pl \
--- xindy.git.orig/make-rules/inputenc/Makefile.in
+++ xindy.git/make-rules/inputenc/Makefile.in
@@ -154,7 +154,7 @@
 top_build_prefix = @top_build_prefix@
 top_builddir = @top_builddir@
 top_srcdir = @top_srcdir@
-modulesdir = $(pkglibdir)/modules
+modulesdir = $(pkgdatadir)
 inputencdir = $(modulesdir)/tex/inputenc
 INPUTENCS = \
 	cp1250.xdy \
--- xindy.git.orig/make-rules/styles/Makefile.in
+++ xindy.git/make-rules/styles/Makefile.in
@@ -154,7 +154,7 @@
 top_build_prefix = @top_build_prefix@
 top_builddir = @top_builddir@
 top_srcdir = @top_srcdir@
-modulesdir = $(pkglibdir)/modules
+modulesdir = $(pkgdatadir)
 stylesdir = $(modulesdir)/styles
 STYLES = \
 	example.xdy \
--- xindy.git.orig/modules/base/Makefile.in
+++ xindy.git/modules/base/Makefile.in
@@ -154,7 +154,7 @@
 top_build_prefix = @top_build_prefix@
 top_builddir = @top_builddir@
 top_srcdir = @top_srcdir@
-modulesdir = $(pkglibdir)/modules
+modulesdir = $(pkgdatadir)
 basedir = $(modulesdir)/base
 RULES = \
 	book-order.xdy \
--- xindy.git.orig/modules/class/Makefile.in
+++ xindy.git/modules/class/Makefile.in
@@ -154,7 +154,7 @@
 top_build_prefix = @top_build_prefix@
 top_builddir = @top_builddir@
 top_srcdir = @top_srcdir@
-modulesdir = $(pkglibdir)/modules
+modulesdir = $(pkgdatadir)
 classdir = $(modulesdir)/class
 RULES = \
 	pagenums.xdy
--- xindy.git.orig/modules/lang/german/Makefile.in
+++ xindy.git/modules/lang/german/Makefile.in
@@ -154,7 +154,7 @@
 top_build_prefix = @top_build_prefix@
 top_builddir = @top_builddir@
 top_srcdir = @top_srcdir@
-langdir = $(pkglibdir)/modules/lang
+langdir = $(pkgdatadir)/lang
 germandir = $(langdir)/german
 RULES = \
 	din5007.xdy \
--- xindy.git.orig/modules/lang/latin/Makefile.in
+++ xindy.git/modules/lang/latin/Makefile.in
@@ -154,7 +154,7 @@
 top_build_prefix = @top_build_prefix@
 top_builddir = @top_builddir@
 top_srcdir = @top_srcdir@
-langdir = $(pkglibdir)/modules/lang
+langdir = $(pkgdatadir)/lang
 latindir = $(langdir)/latin
 RULES = \
 	caseisrt.xdy \
--- xindy.git.orig/modules/ord/Makefile.in
+++ xindy.git/modules/ord/Makefile.in
@@ -154,7 +154,7 @@
 top_build_prefix = @top_build_prefix@
 top_builddir = @top_builddir@
 top_srcdir = @top_srcdir@
-modulesdir = $(pkglibdir)/modules
+modulesdir = $(pkgdatadir)
 orddir = $(modulesdir)/ord
 RULES = \
 	letorder.xdy
--- xindy.git.orig/modules/rules/Makefile.in
+++ xindy.git/modules/rules/Makefile.in
@@ -154,7 +154,7 @@
 top_build_prefix = @top_build_prefix@
 top_builddir = @top_builddir@
 top_srcdir = @top_srcdir@
-modulesdir = $(pkglibdir)/modules
+modulesdir = $(pkgdatadir)
 rulesdir = $(modulesdir)/rules
 RULES = \
 	isolatin1-exchange.xdy \
--- xindy.git.orig/modules/styles/Makefile.in
+++ xindy.git/modules/styles/Makefile.in
@@ -154,7 +154,7 @@
 top_build_prefix = @top_build_prefix@
 top_builddir = @top_builddir@
 top_srcdir = @top_srcdir@
-modulesdir = $(pkglibdir)/modules
+modulesdir = $(pkgdatadir)
 texdir = $(modulesdir)/styles
 RULES = basic.xdy makeidx.xdy
 EXTRA_DIST = $(RULES)
--- xindy.git.orig/user-commands/xindy.in
+++ xindy.git/user-commands/xindy.in
@@ -414,11 +414,13 @@
     }
 
     # modules directory
-    if ( -d "$cmd_dir/../modules" ) {	# /opt style
-	$modules_dir = "$cmd_dir/../modules";
-    } elsif ( -d "$lib_dir/modules" ) {	# /usr style
-	$modules_dir = "$lib_dir/modules";
-    } else {
+    $modules_dir = "/usr/share/xindy";
+    unless ( -d $modules_dir ) {
+    #if ( -d "$cmd_dir/../modules" ) {	# /opt style
+    #	$modules_dir = "$cmd_dir/../modules";
+    #} elsif ( -d "$lib_dir/modules" ) {	# /usr style
+    #	$modules_dir = "$lib_dir/modules";
+    #} else {
 	die "$cmd: Cannot locate xindy modules directory";
     }
 
