#! /bin/sh /usr/share/dpatch/dpatch-run
## fix-configure.dpatch by Jörg Sommer <joerg@alea.gnuu.de>
##
## All lines beginning with `## DP:' are a description of the patch.
## DP: The grouping of the check for latex and pdflatex is not correct,
## DP: which causes configure failes with --disable-make-rules and
## DP: --disable-docs. This patch is only a ugly workaround. A better
## DP: patch was send upstream.

@DPATCH@

---
 configure |    8 ++++----
 1 file changed, 4 insertions(+), 4 deletions(-)

--- xindy.git.orig/configure
+++ xindy.git/configure
@@ -2322,7 +2322,7 @@
   BUILDRULES=yes
 fi
 
-test "$BUILDRULES" = "yes"  &&
+test "$BUILDRULES" = "yes"  && {
 for ac_prog in latex elatex lambda
 do
   # Extract the first word of "$ac_prog", so it can be a program name with args.
@@ -2373,7 +2373,7 @@
 $as_echo "$as_me: error: Unable to find a LaTeX application" >&2;}
    { (exit 1); exit 1; }; };
 fi
-
+}
 
  if test "$BUILDRULES" = "yes"; then
   BUILDRULES_TRUE=
@@ -2392,7 +2392,7 @@
   BUILDDOCS=yes
 fi
 
-test "$BUILDDOCS" = "yes"  &&
+test "$BUILDDOCS" = "yes"  && {
 for ac_prog in pdflatex
 do
   # Extract the first word of "$ac_prog", so it can be a program name with args.
@@ -2443,7 +2443,7 @@
 $as_echo "$as_me: error: Unable to find a PDFLaTeX application" >&2;}
    { (exit 1); exit 1; }; };
 fi
-
+}
 
  if test "$BUILDDOCS" = "yes"; then
   BUILDDOCS_TRUE=
