#! /bin/sh /usr/share/dpatch/dpatch-run
## echo-expansion-fix.dpatch by Jörg Sommer <joerg@alea.gnuu.de>
##
## DP: The echo command shipped with the Debian system takes \ as an escape
## DP: sequence. This causes a formfeed is printed in the string "\fenc...". 

@DPATCH@
---
 make-rules/alphabets/Makefile.in |    2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

--- xindy.git.orig/make-rules/alphabets/Makefile.in
+++ xindy.git/make-rules/alphabets/Makefile.in
@@ -2422,7 +2422,7 @@
 	echo "\section{Codepage latin9}" >>$@
 	for i in $(DOCS_LATIN9); do echo "\input{$$i}" >>$@; done
 	echo "\ienc{cp1251}" >>$@
-	echo "\fenc{T2A}" >>$@
+	printf "%s\n" "\fenc{T2A}" >>$@
 	echo "\chapter{Cyrillic scripts}" >>$@
 	echo "\section{Codepage 1251}" >>$@
 	for i in $(DOCS_CYR_1251); do echo "\input{$$i}" >>$@; done
