#! /bin/sh /usr/share/dpatch/dpatch-run
## help-option.dpatch by Jörg Sommer <joerg@alea.gnuu.de>
##
## DP: The commandline option --help of xindy and texindy prints the help
## DP: message to stderr.

@DPATCH@
---
 user-commands/texindy.in |    8 ++++----
 user-commands/xindy.in   |    8 ++++----
 2 files changed, 8 insertions(+), 8 deletions(-)

--- xindy.git.orig/user-commands/texindy.in
+++ xindy.git/user-commands/texindy.in
@@ -413,9 +413,9 @@
 
 sub usage ( ;$ )
 {
-    my $exit_code = shift;
-    $exit_code += 0;			# turn undef into 0
-    print STDERR <<_EOT_
+    my $signal_error = int shift;
+    my $output_handle = $signal_error ? *STDERR{IO} : *STDOUT{IO};
+    print $output_handle <<_EOT_
 
 usage: $cmd [-V?h] [-qv] [-iglr] [-d magic] [-o outfile.ind] [-t log] \\
             [-L lang] [-C codepage] [-M module] [-I input] [idx0 idx1 ...]
@@ -441,7 +441,7 @@
 
 _EOT_
   ;
-    exit ($exit_code);
+    exit ($signal_error ? 1 : 0);
 }
 
 our ($output_version, $quiet, $verbose, $stdin, @debug,
--- xindy.git.orig/user-commands/xindy.in
+++ xindy.git/user-commands/xindy.in
@@ -431,9 +431,9 @@
 
 sub usage ( ;$ )
 {
-    my $exit_code = shift;
-    $exit_code += 0;			# turn undef into 0
-    print STDERR <<_EOT_
+    my $signal_error = int shift;
+    my $output_handle = $signal_error ? *STDERR{IO} : *STDOUT{IO};
+    print $output_handle <<_EOT_
 
 usage: $cmd [-V?h] [-qv] [-d magic] [-o outfile.ind] [-t log] \\
             [-L lang] [-C codepage] [-M module] [-I input] \\
@@ -457,7 +457,7 @@
 
 _EOT_
   ;
-    exit ($exit_code);
+    exit ($signal_error ? 1 : 0);
 }
 
 our ($quiet, $verbose, %debug,
